In [3]:
import numpy as np
import os
import pandas as pd

In [4]:
past = './DataSet/datatran'

In [20]:
frames = []
inicio = 2007
fim = 2022
col = ['municipio', 'causa_acidente', 'tipo_acidente', 'classificacao_acidente', 'fase_dia', 'sentido_via', 'condicao_metereologica', 'tipo_pista', 'tracado_via', 'uso_solo', 'mes']
for file in range(inicio,fim):
    print(past + str(file) + '.csv')
    df = pd.read_csv(past + str(file) + '.csv', delimiter = ';',  low_memory=False, encoding='UTF-8', index_col = False)
    df = df.drop(columns=['id'])
    if (file >= 2017):
        df = df.drop(columns=['latitude', 'longitude', 'regional','delegacia', 'uop'])
    frames.append(df)

./DataSet/datatran2007.csv
./DataSet/datatran2008.csv
./DataSet/datatran2009.csv
./DataSet/datatran2010.csv
./DataSet/datatran2011.csv
./DataSet/datatran2012.csv
./DataSet/datatran2013.csv
./DataSet/datatran2014.csv
./DataSet/datatran2015.csv
./DataSet/datatran2016.csv
./DataSet/datatran2017.csv
./DataSet/datatran2018.csv
./DataSet/datatran2019.csv
./DataSet/datatran2020.csv
./DataSet/datatran2021.csv

In [6]:
df1 = pd.DataFrame(pd.concat(frames,ignore_index = True))

In [7]:
df1['data_inversa'] = pd.to_datetime(df1['data_inversa'])
df1['ano'] = df1['data_inversa'].dt.year
df1['mes'] = df1['data_inversa'].dt.month_name()
df1['dia'] = df1['data_inversa'].dt.day
df1['dia_semana'] = df1['data_inversa'].dt.day_name()
df1['km'] = pd.to_numeric(df1['km'], downcast='integer', errors = 'ignore')
df1['br'] = pd.to_numeric(df1['br'], downcast='float', errors = 'ignore')
df1['horario'] = pd.to_datetime(df1['horario']).dt.time

In [8]:
df[df['km'] == "NaN"]

Empty DataFrame
Columns: [data_inversa, dia_semana, horario, uf, br, km, municipio, causa_acidente, tipo_acidente, classificacao_acidente, fase_dia, sentido_via, condicao_metereologica, tipo_pista, tracado_via, uso_solo, pessoas, mortos, feridos_leves, feridos_graves, ilesos, ignorados, feridos, veiculos]
Index: []

[0 rows x 24 columns]

In [9]:
df1.dtypes

data_inversa              datetime64[ns]
dia_semana                        object
horario                           object
uf                                object
br                                object
km                                object
municipio                         object
causa_acidente                    object
tipo_acidente                     object
classificacao_acidente            object
fase_dia                          object
sentido_via                       object
condicao_metereologica            object
tipo_pista                        object
tracado_via                       object
uso_solo                          object
ano                                int64
pessoas                            int64
mortos                             int64
feridos_leves                      int64
feridos_graves                     int64
ilesos                             int64
ignorados                          int64
feridos                            int64
veiculos                           int64
mes                               object
dia                                int64
dtype: object

In [10]:
df1n = df1.convert_dtypes()
df1n.dtypes

data_inversa              datetime64[ns]
dia_semana                        string
horario                           object
uf                                string
br                                object
km                                object
municipio                         string
causa_acidente                    string
tipo_acidente                     string
classificacao_acidente            string
fase_dia                          string
sentido_via                       string
condicao_metereologica            string
tipo_pista                        string
tracado_via                       string
uso_solo                          string
ano                                Int64
pessoas                            Int64
mortos                             Int64
feridos_leves                      Int64
feridos_graves                     Int64
ilesos                             Int64
ignorados                          Int64
feridos                            Int64
veiculos                           Int64
mes                               string
dia                                Int64
dtype: object

In [11]:
df1n.columns.values

array(['data_inversa', 'dia_semana', 'horario', 'uf', 'br', 'km',
       'municipio', 'causa_acidente', 'tipo_acidente',
       'classificacao_acidente', 'fase_dia', 'sentido_via',
       'condicao_metereologica', 'tipo_pista', 'tracado_via', 'uso_solo',
       'ano', 'pessoas', 'mortos', 'feridos_leves', 'feridos_graves',
       'ilesos', 'ignorados', 'feridos', 'veiculos', 'mes', 'dia'],
      dtype=object)

In [12]:
df1n.columns.values
col = ['municipio', 'causa_acidente', 'tipo_acidente', 'classificacao_acidente', 'fase_dia', 'sentido_via', 'condicao_metereologica', 'tipo_pista', 'tracado_via', 'uso_solo', 'mes']

In [13]:
for i in col:
    df1n[i] = df1n[i].str.normalize('NFKD').str.encode('ascii', errors='ignore').str.decode('utf-8')
    df1n[i] = df1n[i].str.title()

In [14]:
df1n.dropna()

,data_inversa,dia_semana,horario,uf,br,km,municipio,causa_acidente,tipo_acidente,classificacao_acidente,...,pessoas,mortos,feridos_leves,feridos_graves,ilesos,ignorados,feridos,veiculos,mes,dia
0,2007-11-06,Tuesday,15:30:00,MG,381,623.2,Oliveira,Falta De Atencao,Colisao Frontal,(Null),...,9,0,4,0,5,0,4,6,November,6
1,2007-11-06,Tuesday,15:30:00,MG,381,623.2,Oliveira,Falta De Atencao,Colisao Frontal,(Null),...,9,0,4,0,5,0,4,6,November,6
2,2007-08-13,Monday,14:25:00,MG,40,585.5,Itabirito,Outras,Saida De Pista,Com Vitimas Feridas,...,3,0,0,1,2,0,1,1,August,13
3,2007-12-02,Sunday,02:10:00,MA,135,11,Sao Luis,Animais Na Pista,Atropelamento De Animal,Com Vitimas Fatais,...,5,2,2,1,0,0,3,1,December,2
4,2007-11-20,Tuesday,05:30:00,CE,222,30.8,Caucaia,Defeito Mecanico Em Veiculo,Capotamento,Com Vitimas Feridas,...,1,0,1,0,0,0,1,1,November,20
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1877594,2021-11-05,Friday,05:20:00,ES,101.0,"388,5",Rio Novo Do Sul,Velocidade Incompativel,Tombamento,Com Vitimas Feridas,...,1,0,0,1,0,0,1,1,November,5
1877595,2021-05-27,Thursday,06:20:00,ES,101.0,346,Guarapari,Condutor Deixou De Manter Distancia Do Veiculo...,Colisao Traseira,Com Vitimas Feridas,...,2,0,1,0,1,0,1,2,May,27
1877596,2021-05-22,Saturday,06:55:00,SC,101.0,"180,4",Governador Celso Ramos,Velocidade Incompativel,Colisao Com Objeto,Com Vitimas Fatais,...,1,1,0,0,0,0,0,1,May,22
1877597,2021-03-15,Monday,12:15:00,MG,50.0,"83,5",Uberlandia,Reacao Tardia Ou Ineficiente Do Condutor,Engavetamento,Com Vitimas Feridas,...,3,0,1,0,0,2,1,3,March,15
1877598,2021-11-01,Monday,11:15:00,RJ,493.0,70,Duque De Caxias,Condutor Dormindo,Saida De Leito Carrocavel,Com Vitimas Feridas,...,1,0,0,1,0,0,1,1,November,1

In [15]:
df1n

,data_inversa,dia_semana,horario,uf,br,km,municipio,causa_acidente,tipo_acidente,classificacao_acidente,...,pessoas,mortos,feridos_leves,feridos_graves,ilesos,ignorados,feridos,veiculos,mes,dia
0,2007-11-06,Tuesday,15:30:00,MG,381,623.2,Oliveira,Falta De Atencao,Colisao Frontal,(Null),...,9,0,4,0,5,0,4,6,November,6
1,2007-11-06,Tuesday,15:30:00,MG,381,623.2,Oliveira,Falta De Atencao,Colisao Frontal,(Null),...,9,0,4,0,5,0,4,6,November,6
2,2007-08-13,Monday,14:25:00,MG,40,585.5,Itabirito,Outras,Saida De Pista,Com Vitimas Feridas,...,3,0,0,1,2,0,1,1,August,13
3,2007-12-02,Sunday,02:10:00,MA,135,11,Sao Luis,Animais Na Pista,Atropelamento De Animal,Com Vitimas Fatais,...,5,2,2,1,0,0,3,1,December,2
4,2007-11-20,Tuesday,05:30:00,CE,222,30.8,Caucaia,Defeito Mecanico Em Veiculo,Capotamento,Com Vitimas Feridas,...,1,0,1,0,0,0,1,1,November,20
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1877594,2021-11-05,Friday,05:20:00,ES,101.0,"388,5",Rio Novo Do Sul,Velocidade Incompativel,Tombamento,Com Vitimas Feridas,...,1,0,0,1,0,0,1,1,November,5
1877595,2021-05-27,Thursday,06:20:00,ES,101.0,346,Guarapari,Condutor Deixou De Manter Distancia Do Veiculo...,Colisao Traseira,Com Vitimas Feridas,...,2,0,1,0,1,0,1,2,May,27
1877596,2021-05-22,Saturday,06:55:00,SC,101.0,"180,4",Governador Celso Ramos,Velocidade Incompativel,Colisao Com Objeto,Com Vitimas Fatais,...,1,1,0,0,0,0,0,1,May,22
1877597,2021-03-15,Monday,12:15:00,MG,50.0,"83,5",Uberlandia,Reacao Tardia Ou Ineficiente Do Condutor,Engavetamento,Com Vitimas Feridas,...,3,0,1,0,0,2,1,3,March,15
1877598,2021-11-01,Monday,11:15:00,RJ,493.0,70,Duque De Caxias,Condutor Dormindo,Saida De Leito Carrocavel,Com Vitimas Feridas,...,1,0,0,1,0,0,1,1,November,1

In [17]:
for i in col:
    indexn = df1n[df1n[i] == "(Null)"].index
    df1n.drop(indexn , inplace=True)
    indexn = df1n[df1n[i] == "(null)"].index
    df1n.drop(indexn , inplace=True)

In [18]:
df1n

,data_inversa,dia_semana,horario,uf,br,km,municipio,causa_acidente,tipo_acidente,classificacao_acidente,...,pessoas,mortos,feridos_leves,feridos_graves,ilesos,ignorados,feridos,veiculos,mes,dia
2,2007-08-13,Monday,14:25:00,MG,40,585.5,Itabirito,Outras,Saida De Pista,Com Vitimas Feridas,...,3,0,0,1,2,0,1,1,August,13
3,2007-12-02,Sunday,02:10:00,MA,135,11,Sao Luis,Animais Na Pista,Atropelamento De Animal,Com Vitimas Fatais,...,5,2,2,1,0,0,3,1,December,2
4,2007-11-20,Tuesday,05:30:00,CE,222,30.8,Caucaia,Defeito Mecanico Em Veiculo,Capotamento,Com Vitimas Feridas,...,1,0,1,0,0,0,1,1,November,20
5,2007-12-16,Sunday,17:40:00,MA,230,14,Barao De Grajau,Outras,Capotamento,Com Vitimas Feridas,...,1,0,0,1,0,0,1,1,December,16
6,2007-05-03,Thursday,08:10:00,PR,277,584.4,Cascavel,Outras,Colisao Lateral,Sem Vitimas,...,2,0,0,0,2,0,0,2,May,3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1877594,2021-11-05,Friday,05:20:00,ES,101.0,"388,5",Rio Novo Do Sul,Velocidade Incompativel,Tombamento,Com Vitimas Feridas,...,1,0,0,1,0,0,1,1,November,5
1877595,2021-05-27,Thursday,06:20:00,ES,101.0,346,Guarapari,Condutor Deixou De Manter Distancia Do Veiculo...,Colisao Traseira,Com Vitimas Feridas,...,2,0,1,0,1,0,1,2,May,27
1877596,2021-05-22,Saturday,06:55:00,SC,101.0,"180,4",Governador Celso Ramos,Velocidade Incompativel,Colisao Com Objeto,Com Vitimas Fatais,...,1,1,0,0,0,0,0,1,May,22
1877597,2021-03-15,Monday,12:15:00,MG,50.0,"83,5",Uberlandia,Reacao Tardia Ou Ineficiente Do Condutor,Engavetamento,Com Vitimas Feridas,...,3,0,1,0,0,2,1,3,March,15
1877598,2021-11-01,Monday,11:15:00,RJ,493.0,70,Duque De Caxias,Condutor Dormindo,Saida De Leito Carrocavel,Com Vitimas Feridas,...,1,0,0,1,0,0,1,1,November,1

In [19]:
df1n.to_csv('DataSet/Final/DataSet' + str(inicio) + '_' + str(fim-1) + '.csv', index=False, sep = ';', encoding="UTF-8")